# Generated by Django 3.0.5 on 2021-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
